name: Update Subscription Content

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次抓取和更新
  workflow_dispatch:     # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch subscription content
        run: curl -s https://tizi.239000.xyz/download/sub -o sub.txt

      - name: Generate index.html with <pre> wrapper
        run: |
          echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Subscription</title></head><body><pre>' > index.html
          cat sub.txt >> index.html
          echo '</pre></body></html>' >> index.html

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Update subscription [skip ci]" || echo "No changes to commit"
          git push
